spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:http://localhost:8080/dd_net?serverTimeZone=Asia/Shanghai&useSSL=true
    username: root
    password: 123456
  mvc:
    static-path-pattern: /static/**
  #  热部署
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  devtools:
    restart:
      additional-paths: src/main/java
  freemarker:
    cache: false